// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ystdpxvtwgdqzzprntpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdGRweHZ0d2dkcXp6cHJudHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjAxOTUsImV4cCI6MjA1ODkzNjE5NX0.JyPxaWNXi7Bo7SSj5muOTeeUBVazngBRBcCUb8nS2zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);